# Generated by Django 5.1.1 on 2024-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_variantoption_varianttype_variantdetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantdetail",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
